scripts:
  - &install_npm_dependencies
    name: Install npm dependencies
    script: cd .. && npm install && npm run install:shared && npm run build:shared && npm run install:mobile
  - &set_android_sdk
    name: Set Android SDK location
    script: echo "sdk.dir=$ANDROID_SDK_ROOT" > "$FCI_BUILD_DIR/mobile/android/local.properties"
  - &set_up_keys
    name: Set up keystore
    script: |
      echo $FCI_BUILD_DIR
      echo $CM_KEYSTORE | base64 --decode > "$FCI_BUILD_DIR/mobile/android/app/$CM_KEYSTORE_PATH"
      cat >> "$FCI_BUILD_DIR/mobile/android/keystore.properties" << EOF
      storePassword=$CM_KEYSTORE_PASSWORD
      keyPassword=$CM_KEY_ALIAS_PASSWORD
      keyAlias=$CM_KEY_ALIAS
      storeFile=$CM_KEYSTORE_PATH
      EOF
  - &set-env-vars
    name: Create .env file and set variables
    script: |
      cat >> .env << EOF
      API_ORIGIN_URL = $API_ORIGIN_URL
      APP_HOST = $APP_HOST
      APP_SCHEME = $APP_SCHEME
      EOF
  - &set_up_android_updated_build_number
    name: Set up updated build number
    script: |
      LATEST_GOOGLE_PLAY_BUILD_NUMBER=$(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks=internal)
      if [ -z LATEST_BUILD_NUMBER ]; then
        UPDATED_BUILD_NUMBER=$BUILD_NUMBER
      else
        UPDATED_BUILD_NUMBER=$(($LATEST_GOOGLE_PLAY_BUILD_NUMBER + 1))
      fi

      echo $UPDATED_BUILD_NUMBER > "$FCI_BUILD_DIR/mobile/android/app/versionCode"

      UPDATED_VERSION_NAME=$(<"$FCI_BUILD_DIR/mobile/android/app/versionName" | awk -F. -v OFS=. '{$NF = $UPDATED_BUILD_NUMBER ; print}')
      echo $UPDATED_BUILD_NUMBER
      echo $UPDATED_VERSION_NAME
      echo $UPDATED_VERSION_NAME > "$FCI_BUILD_DIR/mobile/android/app/versionName"
workflows:
  react-native-android:
    name: React Native Android App
    working_directory: mobile
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      node: 16.15.0
      npm: 8.11.0
      groups:
        - keystore_credentials
        - env_vars
        - google_play
      vars:
        PACKAGE_NAME: 'com.guruhub'
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: development
          include: true
          source: true
      cancel_previous_builds: true
    when:
      changeset:
        includes:
          - 'mobile/'
    scripts:
      - *install_npm_dependencies
      - *set_android_sdk
      - *set_up_keys
      - *set-env-vars
      - *set_up_android_updated_build_number
      - name: Build Android release
        script: |
          cd android && ./gradlew clean bundleRelease
    artifacts:
      - android/app/build/outputs/**/*.aab
    publishing:
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
